Internal Server Error: /print_invoice/
Traceback (most recent call last):
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\tss\views.py", line 73, in print_invoice
    html_string = render_to_string('sitemessagesRep.html', [])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\template\backends\django.py", line 57, in render
    context = make_context(
              ^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\template\context.py", line 278, in make_context
    raise TypeError(
TypeError: context must be a dict rather than list.
Relative URI reference without a base URI: <link href="/static/css/bootstrap.min.css">
Relative URI reference without a base URI: <link href="/static/css/bootstrap.min.css">
Relative URI reference without a base URI: <link href="/static/css/bootstrap.min.css">
Relative URI reference without a base URI: <link href="/static/css/bootstrap.min.css">
Relative URI reference without a base URI: <link href="/static/css/bootstrap.min.css">
Relative URI reference without a base URI: <link href="/static/css/bootstrap.min.css">
Relative URI reference without a base URI: <link href="/static/css/bootstrap.min.css">
Relative URI reference without a base URI: <link href="/static/css/bootstrap.min.css">
Relative URI reference without a base URI: <link href="/static/css/bootstrap.min.css">
Relative URI reference without a base URI: <link href="/static/css/bootstrap.min.css">
Relative URI reference without a base URI: <link href="/static/css/bootstrap.min.css">
Relative URI reference without a base URI: <link href="/static/css/bootstrap.min.css">
Relative URI reference without a base URI: <link href="/static/css/bootstrap.min.css">
Relative URI reference without a base URI: <link href="/static/css/bootstrap.min.css">
Internal Server Error: /print_invoice/
Traceback (most recent call last):
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\db\models\query.py", line 587, in aggregate
    arg.default_alias
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\db\models\aggregates.py", line 109, in default_alias
    raise TypeError("Complex expressions require an alias")
TypeError: Complex expressions require an alias

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\tss\views.py", line 72, in print_invoice
    msgcounts = sitemessages.aggregate(Count(id))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\db\models\query.py", line 589, in aggregate
    raise TypeError("Complex aggregates require an alias")
TypeError: Complex aggregates require an alias
Relative URI reference without a base URI: <link href="/static/css/bootstrap.min.css">
Relative URI reference without a base URI: <link href="/static/css/bootstrap.min.css">
Internal Server Error: /print_invoice/
Traceback (most recent call last):
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\tss\views.py", line 73, in print_invoice
    html_string = render_to_string('sitemessagesRep.html', {'sitemessages':sitemessages, 'total': msgcounts('rows')})
                                                                                              ^^^^^^^^^^^^^^^^^
TypeError: 'dict' object is not callable
Internal Server Error: /print_invoice/
Traceback (most recent call last):
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\tss\views.py", line 73, in print_invoice
    html_string = render_to_string('sitemessagesRep.html', {'sitemessages':sitemessages, 'total': msgcounts['rows']})
                                                                                              ~~~~~~~~~^^^^^^^^
KeyError: 'rows'
Internal Server Error: /print_invoice/
Traceback (most recent call last):
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\.venv\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mehrdad\CartonAfzar\tss\views.py", line 73, in print_invoice
    html_string = render_to_string('sitemessagesRep.html', {'sitemessages':sitemessages, 'total': msgcounts['id__Count']})
                                                                                              ^^^^^^^^^^^^^^^^^
KeyError: 'id__'
